# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Check source code quality

on:
  pull_request:
    branches: ["main"]

jobs:
  code_quality:
    name: Check source code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      # Get dart dependencies.
      - name: Install dependencies
        run: dart pub get --no-example

      # Statically analyze the Dart code for any errors.
      - name: Analyze project source
        run: dart analyze lib bin

      # Check for any formatting issues in the code.
      - name: Verify formatting
        run: dart format --set-exit-if-changed lib bin
